### ISSUE TITLE
Сделать рабочее общение в чате

### ISSUE THREAD

**Issue by MaxioN03** [yandex-shri-minsk-2018/repo-team-4#46]
Общение в чате с подпиской, при котором новые сообщения буду появляться без обновления страницы.
Желательно организовать такую структуру, чтобы в списке чатов тоже можно было получить инфу о непрочитанных сообщениях.

**Comment by Tocher** [comment]
лучше разделим на 2 таска.
тут нужно реализовать подписку на сообщения и вывод их в чате.
